/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsertoDeTvEmMaringaRouteImport } from './routes/conserto-de-tv-em-maringa'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ServicosRouteImport } from './routes/servicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsertoDeTvEmMaringaRoute = ConsertoDeTvEmMaringaRouteImport.update({
  id: '/conserto-de-tv-em-maringa',
  path: '/conserto-de-tv-em-maringa',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conserto-de-tv-em-maringa': typeof ConsertoDeTvEmMaringaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conserto-de-tv-em-maringa': typeof ConsertoDeTvEmMaringaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conserto-de-tv-em-maringa': typeof ConsertoDeTvEmMaringaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conserto-de-tv-em-maringa' | '/diagnostico' | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conserto-de-tv-em-maringa' | '/diagnostico' | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/conserto-de-tv-em-maringa'
    | '/diagnostico'
    | '/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsertoDeTvEmMaringaRoute: typeof ConsertoDeTvEmMaringaRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conserto-de-tv-em-maringa': {
      id: '/conserto-de-tv-em-maringa'
      path: '/conserto-de-tv-em-maringa'
      fullPath: '/conserto-de-tv-em-maringa'
      preLoaderRoute: typeof ConsertoDeTvEmMaringaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsertoDeTvEmMaringaRoute: ConsertoDeTvEmMaringaRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
